baseURL = "http://camptocamp.github.io/conplicity/"
title = "Conplicity"
languageCode = "en-us"
theme = "elate"

[params]

  #custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Camptocamp"
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Conplicity"
    #home = "<i class='icon-home'></i>Home"
    #work = "Install"
    #testimonials = "Testimonials"
	services = "<i class='icon-star'></i>Features"
    #about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    [[menu.postpend]]
      url = "https://github.com/camptocamp/conplicity"
      name = "<i class='icon-github'></i>Github"
      weight = 10

    [[menu.postpend]]
      url = "http://www.camptocamp.com"
      name = "<i class='icon-globe'></i>Camptocamp"
      weight = 10

  # Hero section
  [params.hero]
    title = "![Conplicity](images/conplicity_small.png) <p>Conplicity</p>"
    subtitle = 'Automatic backups for Docker containers.'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Install from source"
    description = '''
```shell
$ go get github.com/camptocamp/conplicity
```
'''
    #url = "#"
    #button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Example usage"
    description = '''
```shell
$ conplicity \
  -u s3+http://s3-eu-west-1.amazonaws.com/<my_bucket>/<my_dir> \
  --aws-access-key-id=<my_key_id> \
  --aws-secret-key-id=<my_secret_key>
```
'''
    #url = "#"
    #button = "Copy"
    icon = "icon-wrench"
  #  img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch with Docker"
    description = '''
```shell
$ docker run -v /var/run/docker.sock:/var/run/docker.sock:ro  --rm -ti \
   -e CONPLICITY_TARGET_URL=s3+http://s3-eu-west-1.amazonaws.com/<my_bucket>/<my_dir> \
   -e AWS_ACCESS_KEY_ID=<my_key_id> \
   -e AWS_SECRET_ACCESS_KEY=<my_secret_key> \
     camptocamp/conplicity
```
'''
    #url = "#"
    #button = "Why us?"
    icon = "icon-rocket"
  #  img = "img_10.jpg"

  #[params.intro.video]
  #  enable = true
  #  title = "Watch the video"
  #  icon = "icon-play2"
  #  url = "https://vimeo.com/channels/staffpicks/93951774"


  # Services section
  [params.services]
    enable = true
    title = "Features"
    description = "Conplicity allows to backup Docker volumes using the Duplicity, RClone, and Restic engines."

    [[params.services.item]]
      title = "Built for Docker"
      description = "Conplicity plugs onto the Docker socket to detect local volumes, automatically."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Prometheus Ready"
      description = "Prometheus Support is built-in to easily ship metrics each time conplicity runs."
      icon = "icon-speedometer"

    [[params.services.item]]
      title = "Multiple Clouds"
      description = "Conplicity supports both AWS and Swift as bucket providers."
      icon = "icon-cloud-upload"

    [[params.services.item]]
      title = "Multiple Engines"
      description = "Conplicity uses Duplicity, RClone and Restic as backends to give you full control of your backup mode."
      icon = "icon-puzzle"

  # Footer section
  [params.footer]
    enable = true
    copyright = '[![Camptocamp](images/camptocamp.png)](https://www.camptocamp.com)'
    links = [
        ["icon-globe", "https://www.camptocamp.com"],
        ["icon-twitter", "https://twitter.com/camptocamp"],
        ["icon-github", "https://github.com/camptocamp"]
      ]
