language: go
sudo: required
services: docker
go_import_path: github.com/camptocamp/bivac
go:
  - "1.11"
install:
  - go get github.com/bradfitz/goimports
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/dep/cmd/dep
script:
  - build-binary
  - build-docker-image
  - coverage
jobs:
  include:
    - stage: build-binary
      script: make
    - stage: build-docker-image
      script: docker build .
    - stage: coverage
      if: repo = camptocamp/bivac
      script:
        - make test
        - "$HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage"
