name: bivac
home: https://github.com/camptocamp/bivac
icon: https://raw.githubusercontent.com/camptocamp/bivac/master/img/bivac_small.png
version: 0.0.1
appVersion: latest
description: 'backup interface for volumes attached to containers'
keywords:
  - backup
  - bivac
  - restic
  - volume
  - kubernetes
  - openshift
sources:
  - https://github.com/camptocamp/bivac
maintainers:
  - name: Camptocamp
    email: info@camptocamp.com
