name: Integration tests - Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-tests-docker-raw:
    name: Backup raw data
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build --build-arg GO_VERSION=1.19 --build-arg GOOS=linux --build-arg GOARCH=amd64 --build-arg RESTIC_VERSION=v0.14.0 -t bivac-testing .

      - name: Run raw data test case
        run: ./tests/raw
        working-directory: ./test/integration/docker/

  integration-tests-docker-mysql:
    name: Backup MySQL database
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build --build-arg GO_VERSION=1.19 --build-arg GOOS=linux --build-arg GOARCH=amd64 --build-arg RESTIC_VERSION=v0.14.0 -t bivac-testing .

      - name: Run MySQL test case
        run: ./tests/mysql
        working-directory: ./test/integration/docker/

  integration-tests-docker-postgres:
    name: Backup PostgreSQL database
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build --build-arg GO_VERSION=1.19 --build-arg GOOS=linux --build-arg GOARCH=amd64 --build-arg RESTIC_VERSION=v0.14.0 -t bivac-testing .

      - name: Run PostgreSQL test case
        run: ./tests/postgres
        working-directory: ./test/integration/docker/
